name: xgboost
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask=2.21.0
  - pandas=1.0.5
  - coiled
  - xgboost
  - dask-ml
  - dask-xgboost
  - scikit-learn
  - s3fs
  - python-snappy
  - fastparquet
  - matplotlib
